name: Snb Basket
on:
  schedule:
    - cron: '0 8 1 * *'
  workflow_dispatch: # Allow to manually trigger
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download File
        run: |
          cd snbbasket
          curl https://www.snb.ch/public/en/rss/repos | grep -o '<link>.*xlsx</link>' | sed 's/\(<link>\|<\/link>\)//g' | xargs -n 1 wget
          last=$(date --date="$(date +'%Y-%m-01') - 1 second" +%s)
          for FILENAME in *.xlsx; do mv $FILENAME $(date -d @$last '+%Y-%m-%d')_$FILENAME; done
          mv -f *full.en.xlsx full/
          mv -f *modifications.en.xlsx modifications/
      - name: Commit and push changes
        run: |
          cd snbbasket
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add full/$(date -d @$last '+%Y-%m-%d')*.xlsx
          git add modifications/$(date -d @$last '+%Y-%m-%d')*.xlsx
          git commit -m "Upload new snb basket"
          git push
